sources:
  github:
    enabled: false
    repositories:
      # Core LLM provider repositories
      - owner: openai
        repo: openai-python
      - owner: openai
        repo: openai-node
      - owner: openai
        repo: openai-cookbook
      - owner: langchain-ai
        repo: langchain
    max_issues_per_repo: 10000
    days_back: 1365
  stackoverflow:
    enabled: true
    tags:
      # Focus on highest-signal tags only
      - openai-api
      - langchain
      - gpt-4
      - chatgpt-api
    max_questions_per_tag: 5000000
    days_back: 1365

deduplication:
  enabled: true
  similarity_threshold: 0.8
  title_weight: 0.6
  body_weight: 0.4

pipeline_steps:
  data_acquisition: true
  keyword_filtering: true
  llm_screening: true

llm_screening:
  mode: traditional
  model: gpt-4.1
  temperature: 0.1
  max_tokens: 2000
  provider: openai 