sources:
  github:
    enabled: true
    repositories:
      - owner: openai
        repo: openai-python
    max_issues_per_repo: 10
    days_back: 1000
  stackoverflow:
    enabled: true
    tags:
      - openai-api
      - langchain
    max_questions_per_tag: 10
    days_back: 1000

deduplication:
  enabled: true
  similarity_threshold: 0.8
  title_weight: 0.6
  body_weight: 0.4

pipeline_steps:
  data_acquisition: true
  keyword_filtering: true
  llm_screening: true

llm_screening:
  mode: traditional
  model: gpt-4.1
  temperature: 0.1
  max_tokens: 2000
  provider: openai 