# List of GitHub repositories to fetch issues from
repositories:
  - ethereum/solidity
  - OpenZeppelin/openzeppelin-contracts
  - ConsenSys/smart-contract-best-practices
  - crytic/slither
  - trailofbits/manticore
  # Add more repositories as needed 